theme = "catppuccin_frappe"

[editor]
bufferline = "multiple"
rulers = [80]

[editor.statusline]
center = ["version-control"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace]
render = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" 

[keys.normal."#"]
"+" = ":set-option lsp.display-inlay-hints true"
"*" = ":set-option whitespace.render all"
"minus" = [":set-option lsp.display-inlay-hints false", ":set-option whitespace.render none"]

[keys.insert]
j = { k = "normal_mode" }
